backend:
  name: github
  repo: robertistok/personal-website
  branch: master

media_folder: "static/media"
public_folder: "/media"

collections:
  - name: "post"
    label: "Post"
    folder: "content/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - {
          label: "Template",
          name: "template",
          widget: "hidden",
          default: "post",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string" }
      - {
          label: "Draft",
          name: "draft",
          widget: "boolean",
          default: false,
          required: false,
        }
      - {
          label: "Featured",
          name: "featured",
          widget: "boolean",
          default: false,
          required: false,
        }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Cover", name: "cover", widget: "string", required: false }
      - { label: "Category", name: "category", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Tags", name: "tags", widget: "list", required: false }
